#
# Copyright 2010-2016 Fabric Software Inc. All rights reserved.
#

Import('parentEnv', 'STAGE_DIR')

aliases = []
aliases += SConscript('Oculus/SConscript', exports = {'parentEnv': parentEnv, 'STAGE_DIR': STAGE_DIR}, duplicate=0)
aliases += SConscript('OculusForRTR2/SConscript', exports = {'parentEnv': parentEnv, 'STAGE_DIR': STAGE_DIR}, duplicate=0)

Return('aliases')
